[Audio]
Volume=100

[General]
FileDialogLastLocation=file:///run/media/Frankie/FWQ/vid/Cosmic Princess Kaguya
LastPlayedFile=file:///run/media/Frankie/FWQ/vid/Cosmic Princess Kaguya/Cosmic Princess Kaguya.mkv
