[FileDialog]
history=@Invalid()
lastVisited=file:///run/media/Frankie/FWQ/vid/Kagejitsu/[Nekomoe kissaten&VCB-Studio] Kage no Jitsuryokusha ni Naritakute! S2 [Ma10p_1080p]
qtVersion=5.15.18
viewMode=Detail
