// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "1f1113c1-c819-45f5-8602-4fcc5862638a");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1778335368);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1778335367);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "4e31f119-2b22-49c8-917f-5b01bcc13583");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1778335359);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 166);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v4:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.impressionId", "{21becf33-ee2e-46ef-a359-5a37cb3c8a87}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "151.3.20260419.192959");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.profiles.created", true);
user_pref("browser.profiles.profile-name.updated", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1778131931);
user_pref("browser.search.region", "CN");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20260427205213");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1778335359");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.lastColdStartupCheck", 1778335361);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1778335366);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1778131);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "c284eafb-2fb8-4aa0-b00e-cf52468c8a02");
user_pref("datareporting.dau.cachedUsageProfileID", "98bb238b-41c4-4d6c-89eb-cd40756a93f3");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1775270923689");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "150.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260427205213");
user_pref("extensions.lastAppVersion", "150.0.1");
user_pref("extensions.lastPlatformVersion", "150.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"e5db5a15-2b8e-4f3b-b5ec-de069f3ff850\",\"formautofill@mozilla.org\":\"71e97e2e-0d00-4cee-9089-859f0e3c6f10\",\"ipp-activator@mozilla.com\":\"d2a36e31-0ef7-4957-b04b-0342d56b3963\",\"pictureinpicture@mozilla.org\":\"b6c4e255-f847-4866-b6ef-96fe4da5b904\",\"addons-search-detection@mozilla.com\":\"9a0e74b5-818e-4a06-8767-5f9f3637db66\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"4aad006f-6ce6-42cb-9f5e-93ca80c4f3f2\",\"default-theme@mozilla.org\":\"e460802a-d5c6-47f3-aebf-efe8bf54b4b0\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "2f305126-0b87-4caf-aa8f-7c3d09af6932");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.storeID", "7693f339");
user_pref("toolkit.startup.last_success", 1778335357);
user_pref("toolkit.telemetry.cachedClientID", "1e602ce8-01e5-423b-bb24-e51afa64e217");
user_pref("toolkit.telemetry.cachedProfileGroupID", "265220b6-fc09-4048-8bb8-cc64037b0c0e");
user_pref("toolkit.telemetry.previousBuildID", "20260427205213");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
